# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{laser}
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Edgar"]
  s.date = %q{2010-12-16}
  s.default_executable = %q{laser}
  s.description = %q{Laser is an advanced static analysis tool for Ruby.}
  s.email = %q{michael.j.edgar@dartmouth.edu}
  s.executables = ["laser"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO.md",
     "VERSION",
     "bin/laser",
     "features/step_definitions/laser_steps.rb",
     "features/support/env.rb",
     "features/support/testdata/1_input",
     "features/support/testdata/1_output",
     "features/support/testdata/2_input",
     "features/support/testdata/2_output",
     "features/support/testdata/3_input",
     "features/support/testdata/3_output",
     "features/support/testdata/4_input",
     "features/support/testdata/4_output",
     "features/laser.feature",
     "lib/laser.rb",
     "lib/laser/advice/advice.rb",
     "lib/laser/advice/comment_advice.rb",
     "lib/laser/analysis/annotations.rb",
     "lib/laser/analysis/annotations/next_annotation.rb",
     "lib/laser/analysis/annotations/parent_annotation.rb",
     "lib/laser/analysis/annotations/scope_annotation.rb",
     "lib/laser/analysis/lexical_analysis.rb",
     "lib/laser/analysis/protocol_registry.rb",
     "lib/laser/analysis/protocols.rb",
     "lib/laser/analysis/scope.rb",
     "lib/laser/analysis/sexp_analysis.rb",
     "lib/laser/analysis/signature.rb",
     "lib/laser/analysis/symbol.rb",
     "lib/laser/analysis/visitor.rb",
     "lib/laser/analysis/laser_class.rb",
     "lib/laser/rake/task.rb",
     "lib/laser/runner.rb",
     "lib/laser/scanner.rb",
     "lib/laser/support/module_extensions.rb",
     "lib/laser/third_party/trollop.rb",
     "lib/laser/warning.rb",
     "lib/laser/warnings/comment_spacing.rb",
     "lib/laser/warnings/extra_blank_lines.rb",
     "lib/laser/warnings/extra_whitespace.rb",
     "lib/laser/warnings/line_length.rb",
     "lib/laser/warnings/misaligned_unindentation.rb",
     "lib/laser/warnings/operator_spacing.rb",
     "lib/laser/warnings/rescue_exception.rb",
     "lib/laser/warnings/semicolon.rb",
     "lib/laser/warnings/useless_double_quotes.rb",
     "spec/advice_specs/advice_spec.rb",
     "spec/advice_specs/comment_advice_spec.rb",
     "spec/advice_specs/spec_helper.rb",
     "spec/analysis_specs/annotations_specs/next_prev_annotation_spec.rb",
     "spec/analysis_specs/annotations_specs/parent_annotation_spec.rb",
     "spec/analysis_specs/annotations_specs/spec_helper.rb",
     "spec/analysis_specs/lexical_analysis_spec.rb",
     "spec/analysis_specs/protocol_registry_spec.rb",
     "spec/analysis_specs/protocols_spec.rb",
     "spec/analysis_specs/scope_spec.rb",
     "spec/analysis_specs/sexp_analysis_spec.rb",
     "spec/analysis_specs/spec_helper.rb",
     "spec/analysis_specs/visitor_spec.rb",
     "spec/analysis_specs/laser_class_spec.rb",
     "spec/rake_specs/spec_helper.rb",
     "spec/rake_specs/task_spec.rb",
     "spec/runner_spec.rb",
     "spec/scanner_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/support_specs/module_extensions_spec.rb",
     "spec/support_specs/spec_helper.rb",
     "spec/warning_spec.rb",
     "spec/warning_specs/comment_spacing_spec.rb",
     "spec/warning_specs/extra_blank_lines_spec.rb",
     "spec/warning_specs/extra_whitespace_spec.rb",
     "spec/warning_specs/line_length_spec.rb",
     "spec/warning_specs/misaligned_unindentation_spec.rb",
     "spec/warning_specs/operator_spacing_spec.rb",
     "spec/warning_specs/rescue_exception_spec.rb",
     "spec/warning_specs/semicolon_spec.rb",
     "spec/warning_specs/spec_helper.rb",
     "spec/warning_specs/useless_double_quotes_spec.rb",
     "spec/laser_spec.rb",
     "status_reports/2010/12/2010-12-14.md",
     "test/third_party_tests/test_trollop.rb",
     "laser.gemspec"
  ]
  s.homepage = %q{http://github.com/michaeledgar/laser}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Analysis and Linting tool for Ruby.}
  s.test_files = [
    "spec/advice_specs/advice_spec.rb",
     "spec/advice_specs/comment_advice_spec.rb",
     "spec/advice_specs/spec_helper.rb",
     "spec/analysis_specs/annotations_specs/next_prev_annotation_spec.rb",
     "spec/analysis_specs/annotations_specs/parent_annotation_spec.rb",
     "spec/analysis_specs/annotations_specs/spec_helper.rb",
     "spec/analysis_specs/lexical_analysis_spec.rb",
     "spec/analysis_specs/protocol_registry_spec.rb",
     "spec/analysis_specs/protocols_spec.rb",
     "spec/analysis_specs/scope_spec.rb",
     "spec/analysis_specs/sexp_analysis_spec.rb",
     "spec/analysis_specs/spec_helper.rb",
     "spec/analysis_specs/visitor_spec.rb",
     "spec/analysis_specs/laser_class_spec.rb",
     "spec/rake_specs/spec_helper.rb",
     "spec/rake_specs/task_spec.rb",
     "spec/runner_spec.rb",
     "spec/scanner_spec.rb",
     "spec/spec_helper.rb",
     "spec/support_specs/module_extensions_spec.rb",
     "spec/support_specs/spec_helper.rb",
     "spec/warning_spec.rb",
     "spec/warning_specs/comment_spacing_spec.rb",
     "spec/warning_specs/extra_blank_lines_spec.rb",
     "spec/warning_specs/extra_whitespace_spec.rb",
     "spec/warning_specs/line_length_spec.rb",
     "spec/warning_specs/misaligned_unindentation_spec.rb",
     "spec/warning_specs/operator_spacing_spec.rb",
     "spec/warning_specs/rescue_exception_spec.rb",
     "spec/warning_specs/semicolon_spec.rb",
     "spec/warning_specs/spec_helper.rb",
     "spec/warning_specs/useless_double_quotes_spec.rb",
     "spec/laser_spec.rb",
     "test/third_party_tests/test_trollop.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby_parser>, [">= 2.0.5"])
      s.add_runtime_dependency(%q<ruby2ruby>, [">= 1.2.4"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<ruby_parser>, [">= 2.0.5"])
      s.add_dependency(%q<ruby2ruby>, [">= 1.2.4"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruby_parser>, [">= 2.0.5"])
    s.add_dependency(%q<ruby2ruby>, [">= 1.2.4"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end
