# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wool}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Edgar"]
  s.date = %q{2010-09-05}
  s.default_executable = %q{wool}
  s.description = %q{Unlike existing lint tools, wool intends solely to examine Ruby code for style issues.}
  s.email = %q{michael.j.edgar@dartmouth.edu}
  s.executables = ["wool"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/wool",
     "lib/wool.rb",
     "lib/wool/scanner.rb",
     "lib/wool/warning.rb",
     "lib/wool/warnings/extra_whitespace.rb",
     "lib/wool/warnings/misaligned_unindentation.rb",
     "lib/wool/warnings/operator_spacing.rb",
     "lib/wool/warnings/semicolon.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/warning_spec.rb",
     "spec/warning_specs/extra_whitespace_spec.rb",
     "spec/warning_specs/misaligned_unindentation_spec.rb",
     "spec/warning_specs/operator_spacing_spec.rb",
     "spec/warning_specs/semicolon_spec.rb",
     "spec/warning_specs/spec_helper.rb",
     "spec/wool_spec.rb"
  ]
  s.homepage = %q{http://github.com/michaeledgar/wool}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Style-focused linter for Ruby code.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/warning_spec.rb",
     "spec/warning_specs/extra_whitespace_spec.rb",
     "spec/warning_specs/misaligned_unindentation_spec.rb",
     "spec/warning_specs/operator_spacing_spec.rb",
     "spec/warning_specs/semicolon_spec.rb",
     "spec/warning_specs/spec_helper.rb",
     "spec/wool_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end
